### ISSUE TITLE
Code doesn't run ......

### ISSUE THREAD

**Issue by XY2323819551** [yuhongqian/ANCE-PRF#3]
Have you really checked your code thoroughly? I found a lot of basic mistakes. For example in "train_encoder.sh"，you have not defined "dataset", you used it in "--train_data_dir ${data_dir}/${dataset}_train_prf"

**Comment by yuhongqian** [comment]
Hi, thank you very much for your interest in our work!  Also thanks a lot for raising the issues! It turned out that I accidentally pushed the wrong version. Please pull the most up-to-date commit and let me know if I made some other stupid mistakes when cleaning up the code.

**Comment by XY2323819551** [comment]
> Hi, thank you very much for your interest in our work! Also thanks a lot for raising the issues! It turned out that I accidentally pushed the wrong version. Please pull the most up-to-date commit and let me know if I made some other stupid mistakes when cleaning up the code.

Thank you very much！ I'll try to reproduce it again！
