### ISSUE TITLE
No such file or directory: 'XXX/marco_output/prf_train.tsv'

### ISSUE THREAD

**Issue by XY2323819551** [yuhongqian/ANCE-PRF#4]
Hi, thanks again for your excellent work! I'm trying to reproduce your experiment, however, I'm having a lot of problems. When I try to get the prf data, I get the following error. How should I fix it? I ran the code strictly as you instructed in README.md. Looking forward to your reply！

(ANCE-PRF-ori) zhangxy@s2:~/QA/ANCE-PRF-main/data_prep$ bash get_prf_data.sh
Generating PRF training data from ANCE top ranking on MARCO training set...
Generated PRF data for all datasets.
(ANCE-PRF-ori) zhangxy@s2:~/QA/ANCE-PRF-main/data_prep$ Loaded 2 chunks of embeddings.
Loaded 2 chunks of embeddings.
Traceback (most recent call last):
  File "get_prf_data.py", line 165, in <module>
    psg_embeds = get_psg_embeds(args, passage_embedding, passage_embedding2id)
  File "get_prf_data.py", line 123, in get_psg_embeds
    with open(tsv_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhangxy/QA/ANCE-PRF-main/data/marco_output/prf_train.tsv'

**Comment by yuhongqian** [comment]
Thanks for the feedback! I commented out some code during testing and forgot to turn them back, which caused `prf_train.tsv` not being generated. Could you try pulling the latest commit and rerun `get_prf_data.sh`?

**Comment by XY2323819551** [comment]
> Thanks for the feedback! I commented out some code during testing and forgot to turn them back, which caused `prf_train.tsv` not being generated. Could you try pulling the latest commit and rerun `get_prf_data.sh`?

Thank you! I ran it successfully！
