### ISSUE TITLE
cannot import name 'StreamingDataset' and 'EmbeddingCache'

### ISSUE THREAD

**Issue by XY2323819551** [yuhongqian/ANCE-PRF#5]
Hi, I guess you missed class 'EmbeddingCache' and 'StreamingDataset' in utils/util.py, which are used in 'preprocess_data.py'
and 'get_ance_embs.py', respectively.

**Comment by yuhongqian** [comment]
Hi, they are added back in the latest commit. My apologies!

**Comment by XY2323819551** [comment]
> My apologies!

Thanks for your quick reply!
