### ISSUE TITLE
TypeError: 'Namespace' object is not iterable

### ISSUE THREAD

**Issue by XY2323819551** [yuhongqian/ANCE-PRF#6]
Now, I came to the last step. However, when I run "bash train_encoder.sh", I encounter a problem and I try to solve it but failed. So what should I do?

Traceback (most recent call last):
  File "/home/zhangxy/QA/ANCE-PRF-main/main.py", line 115, in <module>
    main()
  File "/home/zhangxy/QA/ANCE-PRF-main/main.py", line 94, in main
    trainer.train()
  File "/home/zhangxy/QA/ANCE-PRF-main/runner.py", line 144, in train
    batch = next(train_dataloader_iter)
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/home/zhangxy/QA/ANCE-PRF-main/utils/util.py", line 723, in __iter__
    for i, element in enumerate(self.elements):
TypeError: 'Namespace' object is not iterable

Process finished with exit code 1

**Comment by yuhongqian** [comment]
Hi, I assume that was caused by the naming conflict of `EmbeddingCache` and `StreamingDataset` in `data.py` and `util.py` (sorry for the bad engineering practice...). I resolved the naming conflict in the new commit, could you try pulling it and see if the error is gone?

**Comment by XY2323819551** [comment]
> Hi, I assume that was caused by the naming conflict of `EmbeddingCache` and `StreamingDataset` in `data.py` and `util.py` (sorry for the bad engineering practice...). I resolved the naming conflict in the new commit, could you try pulling it and see if the error is gone?

Thanks for your reply! However, there are still some issues.
(1) You used "passage_cache = EmbeddingCache(passage_collection_path)", do you mean the UtilEmbeddingCache or the EmbeddingCache class in data.py? I have tried both, but I get the same error when I run "bash train_encoder.sh" as shown below.

Traceback (most recent call last):
  File "main.py", line 115, in <module>
    main()
  File "main.py", line 94, in main
    trainer.train()
  File "/home/zhangxy/QA/ANCE-PRF-main/runner.py", line 144, in train
    batch = next(train_dataloader_iter)
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 106, in __iter__
    for rec in records:
  File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 150, in fn
    psg_embeds = ordered_psg_embeds[effective_idx]
IndexError: index 1 is out of bounds for axis 0 with size 0

So how can I solve it?

**Comment by XY2323819551** [comment]
> "passage_cache = EmbeddingCache(passage_collection_path)"

The line "passage_cache = EmbeddingCache(passage_collection_path)" is in run_ann_data_gen.py

**Comment by yuhongqian** [comment]
Looks like this line was not refactored, just made another commit. Hopefully now all function calls to `util.py` use `UtilDataStreaming` and `UtilEmbeddingCache`.  
> > "passage_cache = EmbeddingCache(passage_collection_path)"
> 
> The line "passage_cache = EmbeddingCache(passage_collection_path)" is in run_ann_data_gen.py

**Comment by yuhongqian** [comment]
It seems that it's a different error message this time. Is `ordered_psg_embeds` empty? 
> > Hi, I assume that was caused by the naming conflict of `EmbeddingCache` and `StreamingDataset` in `data.py` and `util.py` (sorry for the bad engineering practice...). I resolved the naming conflict in the new commit, could you try pulling it and see if the error is gone?
> 
> Thanks for your reply! However, there are still some issues. (1) You used "passage_cache = EmbeddingCache(passage_collection_path)", do you mean the UtilEmbeddingCache or the EmbeddingCache class in data.py? I have tried both, but I get the same error when I run "bash train_encoder.sh" as shown below.
> 
> Traceback (most recent call last): File "main.py", line 115, in main() File "main.py", line 94, in main trainer.train() File "/home/zhangxy/QA/ANCE-PRF-main/runner.py", line 144, in train batch = next(train_dataloader_iter) File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch data.append(next(self.dataset_iter)) File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 106, in **iter** for rec in records: File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 150, in fn psg_embeds = ordered_psg_embeds[effective_idx] IndexError: index 1 is out of bounds for axis 0 with size 0
> 
> So how can I solve it?

**Comment by yuhongqian** [comment]
Also the naming conflict should only affect `main.py`, `runner.py`, and `get_eval_metrics.py` because there are `import *` from both `data.py` and `util.py`, making the latter import override the former. 

That means the data preprocessing run before today's naming conflict resolution shouldn't be affected

**Comment by XY2323819551** [comment]
> `main.py`, `runner.py`, and `get_eval_metrics.py`

Ok, thanks. So "EmbeddingCache" and "StreamingDataset" in main.py, runner.py, and get_eval_metrics.py come from data.py？Now main.py, runner.py, and get_eval_metrics.py are correct?

**Comment by XY2323819551** [comment]
> It seems that it's a different error message this time. Is `ordered_psg_embeds` empty?
> 
> > > Hi, I assume that was caused by the naming conflict of `EmbeddingCache` and `StreamingDataset` in `data.py` and `util.py` (sorry for the bad engineering practice...). I resolved the naming conflict in the new commit, could you try pulling it and see if the error is gone?
> > 
> > 
> > Thanks for your reply! However, there are still some issues. (1) You used "passage_cache = EmbeddingCache(passage_collection_path)", do you mean the UtilEmbeddingCache or the EmbeddingCache class in data.py? I have tried both, but I get the same error when I run "bash train_encoder.sh" as shown below.
> > Traceback (most recent call last): File "main.py", line 115, in main() File "main.py", line 94, in main trainer.train() File "/home/zhangxy/QA/ANCE-PRF-main/runner.py", line 144, in train batch = next(train_dataloader_iter) File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch data.append(next(self.dataset_iter)) File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 106, in **iter** for rec in records: File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 150, in fn psg_embeds = ordered_psg_embeds[effective_idx] IndexError: index 1 is out of bounds for axis 0 with size 0
> > So how can I solve it?

Yes，the code line "self.psg_embeds = pickle.load(f)" in data.py seems to fail……
![q](https://user-images.githubusercontent.com/40745058/168739357-7e9c2272-9fee-4d87-908b-e47a781943cf.JPG)

**Comment by yuhongqian** [comment]
> > `main.py`, `runner.py`, and `get_eval_metrics.py`
> 
> Ok, thanks. So "EmbeddingCache" and "StreamingDataset" in main.py, runner.py, and get_eval_metrics.py come from data.py？Now main.py, runner.py, and get_eval_metrics.py are correct?

Yup

**Comment by yuhongqian** [comment]
> > It seems that it's a different error message this time. Is `ordered_psg_embeds` empty?
> > > > Hi, I assume that was caused by the naming conflict of `EmbeddingCache` and `StreamingDataset` in `data.py` and `util.py` (sorry for the bad engineering practice...). I resolved the naming conflict in the new commit, could you try pulling it and see if the error is gone?
> > > 
> > > 
> > > Thanks for your reply! However, there are still some issues. (1) You used "passage_cache = EmbeddingCache(passage_collection_path)", do you mean the UtilEmbeddingCache or the EmbeddingCache class in data.py? I have tried both, but I get the same error when I run "bash train_encoder.sh" as shown below.
> > > Traceback (most recent call last): File "main.py", line 115, in main() File "main.py", line 94, in main trainer.train() File "/home/zhangxy/QA/ANCE-PRF-main/runner.py", line 144, in train batch = next(train_dataloader_iter) File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/zhangxy/anaconda3/envs/ANCE-PRF-ori/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch data.append(next(self.dataset_iter)) File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 106, in **iter** for rec in records: File "/home/zhangxy/QA/ANCE-PRF-main/data.py", line 150, in fn psg_embeds = ordered_psg_embeds[effective_idx] IndexError: index 1 is out of bounds for axis 0 with size 0
> > > So how can I solve it?
> 
> Yes，the code line "self.psg_embeds = pickle.load(f)" in data.py seems to fail…… ![q](https://user-images.githubusercontent.com/40745058/168739357-7e9c2272-9fee-4d87-908b-e47a781943cf.JPG)

Apparently there is something wrong with the passage embedding data. Could you maybe double-check that?

**Comment by XY2323819551** [comment]
> 

Yea, I found the cause of the error, I was using a toy dataset, but the number of chunks was too high. I changed the value of the "ann_chunk_factor" parameter and the program works. Thanks for your patience, you are very nice!
